name: Latest blog post workflow

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://devrenio.github.io/feed.xml"
          comment_tag_name: "BLOG-POST-LIST"
          readme_path: "./README.md"
          max_post_count: 5
