# GitHub Action to generate a snake animation from GitHub contribution graph

name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v3 # Use the latest version v3 for better support
        with:
          # Use the GitHub context variable to automatically get the username
          github_user_name: ${{ github.repository_owner }}

          # Specify the output file path
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push generated file
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Push to a separate branch to keep the main branch clean
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
